version: '3.8'

services:
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    image: pasdf/config-service:latest

  eureka-service:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    image: pasdf/eureka-service:latest
    depends_on:
      - config-service

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    image: pasdf/gateway-service:latest
    depends_on:
      - eureka-service

  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    image: pasdf/client-service:latest
    depends_on:
      - eureka-service

  loan-service:
    build:
      context: ./loan-service
      dockerfile: Dockerfile
    image: pasdf/loan-service:latest
    depends_on:
      - eureka-service

  document-service:
    build:
      context: ./document-service
      dockerfile: Dockerfile
    image: pasdf/document-service:latest
    depends_on:
      - eureka-service

  simulate-service:
    build:
      context: ./simulate-service
      dockerfile: Dockerfile
    image: pasdf/simulate-service:latest
    depends_on:
      - eureka-service

  follow-up-service:
    build:
      context: ./follow-up-service
      dockerfile: Dockerfile
    image: pasdf/follow-up-service:latest
    depends_on:
      - eureka-service

  evaluate-service:
    build:
      context: ./evaluate-service
      dockerfile: Dockerfile
    image: pasdf/evaluate-service:latest
    depends_on:
      - eureka-service
  frontend:
    build:
        context: ../FrontEndPrestaBanco
        dockerfile: Dockerfile
    image: pasdf/frontend:latest