server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
        - id: simulate-service
          uri: lb://simulate-service
          predicates:
            - Path=/simulate/**
        - id: evaluate-service
          uri: lb://evaluate-service
          predicates:
            - Path=/evaluation/**
        - id: follow-up-service
          uri: lb://follow-up-service
          predicates:
            - Path=/follow-up/**
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/document/**