server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
        - id: simulate-service
          uri: lb://simulate-service
          predicates:
            - Path=/simulate/**
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluation/**
        - id: follow-up-service
          uri: lb://follow-up-service
          predicates:
            - Path=/follow-up/**
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/document/**