apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluate-service-deployment
  labels:
    app: evaluate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluate-service
  template:
    metadata:
      labels:
        app: evaluate-service
    spec:
      containers:
        - name: evaluate-service
          image: pasdf/evaluate-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password