apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-up-service-deployment
  labels:
    app: follow-up-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follow-up-service
  template:
    metadata:
      labels:
        app: follow-up-service
    spec:
      containers:
        - name: follow-up-service
          image: pasdf/follow-up-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password